### ISSUE TITLE
Since commit 552d3833 the 'api' folder is missing, yet all the documentation still refers to it

### ISSUE THREAD

**Issue by denhamcoote** [Hygieia/Hygieia#3084] opened 2019-08-12 10:18 UTC
This is making it rather difficult to install, as I'm not an expert in mvn, nmp, mongo or any of the tools you require.

Could you provide (or point me to) some updated documentation, please?

**Comment by rvema** [comment] 2019-08-12 10:42
This is a duplicate of #3074 . please check the issue

**Closed by rvema** 2019-08-12 10:42 UTC

**Comment by denhamcoote** [comment] 2019-08-12 10:52
@rvema Thanks for the prompt response, but closing the issue and redirecting doesn't exactly address the issue I raised.

I found the new API repo, that is not the issue.  The issue is the lack of documentation/ incorrect documentation.  Should I raise a new issue but word the title differently? "Documentation incorrect", perhaps?

I'd really like to use Hygieia, but it's really difficult to get started without guidance ;)

**Comment by rvema** [comment] 2019-08-12 11:13
@denhamcoote Sorry for the inconvenience, We are in the mid of repository migration hence some of the documentation links are not functional. We should be done with this effort in couple of weeks and will fix the documentation asap.

**Comment by denhamcoote** [comment] 2019-08-12 11:17
@rvema Thank you for your efforts - I look forward to being able to get it working :)
