### ISSUE TITLE
UCD not showing up in Hygieia Dashboard

### ISSUE THREAD

**Issue by Samriddhi1** [Hygieia/Hygieia#944] opened 2016-11-14 07:44 UTC
Hi,

My UCD instance in running on a secured https server..I am able to see the udeploy collector running successfully on console but I can not see it coming up on Hygieia Dashboard. Here is my application,properties file for UCD collector: 
```properties
# Database HostName - default is localhost
spring.data.mongodb.host=169.50.118.135

# Database Port - default is 27017
spring.data.mongodb.port=27017

# Database Username - default is blank
spring.data.mongodb.username=samriddhi

# Database Password - default is blank
spring.data.mongodb.password=dbpassword

# Collector schedule (required)
udeploy.cron=0 0/5 * * * *

# UDeploy server (required) - Can provide multiple
udeploy.servers[0]=https://169.50.117.227:8443

# UDeploy user name (required)
udeploy.username=****

# UDeploy password (required)
udeploy.password=****
```

Here is the log file for udeploy collector:

```
2016-11-14 06:28:45,868 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering be
ans for JMX exposure on startup
2016-11-14 06:28:45,885 INFO  com.capitalone.dashboard.Application - Started App
lication in 4.705 seconds (JVM running for 5.743)
2016-11-14 06:30:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 06:30:00,009 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:30:00,009 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 06:30:00,009 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:30:00,681 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 06:30:00,697 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 06:30:00,699 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 06:35:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 06:35:00,005 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:35:00,005 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 06:35:00,005 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:35:00,073 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 06:35:00,078 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 06:35:00,080 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 06:40:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 06:40:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:40:00,003 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 06:40:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:40:00,032 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 06:40:00,037 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 06:40:00,038 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 06:45:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 06:45:00,005 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:45:00,006 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 06:45:00,006 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:45:00,034 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 06:45:00,038 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 06:45:00,040 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 06:50:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 06:50:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:50:00,003 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 06:50:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:50:00,034 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 06:50:00,044 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 06:50:00,049 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 06:55:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 06:55:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:55:00,003 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 06:55:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 06:55:00,027 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 06:55:00,033 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 06:55:00,037 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 07:00:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 07:00:00,009 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:00:00,009 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 07:00:00,009 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:00:00,034 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 07:00:00,037 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 07:00:00,038 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 07:05:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 07:05:00,005 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:05:00,005 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 07:05:00,005 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:05:00,047 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 07:05:00,050 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 07:05:00,052 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 07:10:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 07:10:00,004 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:10:00,004 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 07:10:00,004 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:10:00,029 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 07:10:00,033 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 07:10:00,035 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 07:15:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 07:15:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:15:00,003 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 07:15:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:15:00,044 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 07:15:00,059 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 07:15:00,061 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 07:20:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 07:20:00,002 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:20:00,003 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 07:20:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:20:00,030 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 07:20:00,036 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 07:20:00,040 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 07:25:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 07:25:00,004 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:25:00,004 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 07:25:00,004 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:25:00,025 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 07:25:00,028 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 07:25:00,030 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 07:30:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 07:30:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:30:00,003 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 07:30:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:30:00,026 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 07:30:00,029 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 07:30:00,031 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 07:35:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 07:35:00,004 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:35:00,004 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 07:35:00,004 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:35:00,033 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 07:35:00,037 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 07:35:00,039 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 07:40:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector:
 UDeploy
2016-11-14 07:40:00,003 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:40:00,004 INFO  c.c.d.collector.CollectorTask - https://169.50.117
.227:8443
2016-11-14 07:40:00,004 INFO  c.c.d.collector.CollectorTask - ------------------
------------
2016-11-14 07:40:00,028 INFO  c.c.d.collector.CollectorTask - All apps
 2        0s
2016-11-14 07:40:00,031 INFO  c.c.d.collector.CollectorTask - New apps
 0        0s
2016-11-14 07:40:00,033 INFO  c.c.d.collector.CollectorTask - Finished
          0s
2016-11-14 07:41:18,970 INFO  o.s.c.a.AnnotationConfigApplicationContext - Closi
ng org.springframework.context.annotation.AnnotationConfigApplicationContext@11a
5a616: startup date [Mon Nov 14 06:28:41 UTC 2016]; root of context hierarchy
2016-11-14 07:41:18,972 INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering
JMX-exposed beans on shutdown
2016-11-14 07:41:18,991 INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down Ex
ecutorService 'taskScheduler'
```

Is using HTTPS an issue??

**Comment by tabladrum** [comment] 2016-11-15 21:44
https should not be the issue. Are you using a userid that has visibility to all the apps?

**Comment by Samriddhi1** [comment] 2016-11-17 04:09
yes..I am using the admin userid.

**Comment by Samriddhi1** [comment] 2016-11-18 10:14
I tried running the ucd collector and now i get this error:

2016-11-18 09:15:00,034 ERROR c.c.d.collector.DefaultUDeployClient - Error with
REST url: https://169.50.117.227:8443 /rest/deploy/application
2016-11-18 09:15:00,035 ERROR c.c.d.collector.DefaultUDeployClient - 404 /%20/re
st/deploy/application

**Comment by git4giri** [comment] 2017-04-12 16:23
@Samriddhi1 
What UCD version you are using?
I think its issue with UCD version 6.2.x... as current uDeploy collector is not compatible with  that version.
am I right @tabladrum ?

**Comment by irvingoe** [comment] 2017-06-02 15:48
@git4giri There's an open issue for that #1084

**Comment by rvema** [comment] 2018-09-26 04:15
closing this issue as its a duplicate of #1084

**Closed by rvema** 2018-09-26 04:15 UTC
