### ISSUE TITLE
gitlab scm collector show no pulls and issues data

### ISSUE THREAD

**Issue by lyndomiao** [Hygieia/Hygieia#2730] opened 2019-02-14 13:03 UTC
my gitlab scm collector works,but it only shows the commits data,no any pulls or commits data.How to resovle it?

**Comment by lyndomiao** [comment] 2019-02-14 13:06
@Sbrenthughes can u helo me?

**Comment by Sbrenthughes** [comment] 2019-02-14 13:57
For the branch you are collecting, are there PRs within the last 14days ?

**Comment by lyndomiao** [comment] 2019-02-14 15:25
@Sbrenthughes yes,there are PRs within the last 14days.And there is no error in the container's log

**Comment by Sbrenthughes** [comment] 2019-02-14 15:30
Are the PRs for the branch you have configured in the UI?

**Comment by lyndomiao** [comment] 2019-02-15 01:17
@Sbrenthughes yes,I have configured in the UI,and  the commits data shown in widget is right

**Comment by zhenweiding** [comment] 2019-02-15 08:46
@lyndomiao according to the source code, the gitlab scm collector only get the commits data, no pulls and issues data.

https://github.com/Hygieia/Hygieia/blob/master/collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/collector/GitlabGitCollectorTask.java#L101

https://github.com/Hygieia/Hygieia/blob/master/collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/GitlabGitClient.java

**Comment by Sbrenthughes** [comment] 2019-02-15 13:32
@zhenweiding thanks for looking into this. I should not have assumed that logic was present. Can either of you implement it and make a PR back ?

**Comment by lyndomiao** [comment] 2019-02-17 02:57
@zhenweiding thank u for help!I did not read the Hygieia source code,and I thought Hygieia collector had implemented all the functions.I can implement the function of 'issues count' of Gitlab SCM Collector by Gitlab API '/projects/:id/issues',but I can not find the API to get 'pulls count'.Do u know how to resolve it?

**Comment by rikameajay1** [comment] 2019-02-19 11:18
Gitlab collector doesnt collect previous data even though I added 
**gitlab.commitThresholdDays=45**

Gitlab URI: http://Gitlab-xxxx:80/api/v4/projects/xxxxxxxxxx/repository/commits/?ref_name=master&since=2019-02-19T11:07:30.032Z&per_page=100

Is there any other property file which also needs to be updated?

**Comment by Sbrenthughes** [comment] 2019-02-19 13:55
@rikameajay1 I am not sure your issue is related here. Can you open a new issue?

**Comment by zhenweiding** [comment] 2019-02-20 01:37
> 
> 
> @zhenweiding thank u for help!I did not read the Hygieia source code,and I thought Hygieia collector had implemented all the functions.I can implement the function of 'issues count' of Gitlab SCM Collector by Gitlab API '/projects/:id/issues',but I can not find the API to get 'pulls count'.Do u know how to resolve it?

@lyndomiao There is no 'pull' or 'PR' in GitLab, i think the 'merge requests(MR)' in GitLab is similar to 'pulls(PR)' in GitHub. 
Here is the Gitlab's API:
GET /projects/:id/merge_requests

**Comment by zhenweiding** [comment] 2019-02-21 09:25
@Sbrenthughes I am working on it, i will PR back when it's ready.

**Comment by poojithkumar** [comment] 2019-02-27 09:52
I have facing issues with GitHub

this is my log
[org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=12bee3bd,type=ConfigurationPropertiesRebinder]
2019-02-27 01:42:22,379 INFO com.capitalone.dashboard.Application - Started Application in 15.805 seconds (JVM running for 20.316)
2019-02-27 01:43:00,005 INFO c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-02-27 01:43:00,919 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:43:00,919 INFO c.c.d.collector.CollectorTask - Starting...
2019-02-27 01:43:00,919 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:43:01,564 INFO c.c.d.collector.CollectorTask - Repo Count 0 0s
2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - New Commits 0 0s
2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - New Pulls 0 0s
2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - New Issues 0 0s
2019-02-27 01:43:01,565 INFO c.c.d.collector.CollectorTask - Finished 0s
2019-02-27 01:44:00,001 INFO c.c.d.collector.CollectorTask - Running Collector: GitHub
2019-02-27 01:44:00,053 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:44:00,053 INFO c.c.d.collector.CollectorTask - Starting...
2019-02-27 01:44:00,053 INFO c.c.d.collector.CollectorTask - -----------------------------------
2019-02-27 01:44:00,705 INFO c.c.d.collector.GitHubCollectorTask - {password=, personalAccessToken=, branch=master, userID=, url=https://github.com/poojithkumar/demo/}::master:: get commits
2019-02-27 01:44:00,764 INFO c.c.d.collector.DefaultGitHubClient - Executing https://api.github.com/repos/poojithkumar/demo//commits?sha=master&since=2019-02-13T01:44Z
2019-02-27 01:44:00,943 ERROR c.c.d.collector.DefaultGitHubClient - Cannot decrypt this message
Input length must be multiple of 8 when decrypting with padded cipher
2019-02-27 01:44:01,643 ERROR c.c.d.collector.GitHubCollectorTask - Error fetching commits for:https://github.com/poojithkumar/demo/
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.github.com/repos/poojithkumar/demo/commits?sha=master&since=2019-02-13T01:44Z": Received fatal alert: access_denied; nested exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(DefaultGitHubClient.java:597) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(DefaultGitHubClient.java:99) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHubCollectorTask.java:178) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.0.4.jar!/:3.0.1]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_191]
at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_191]
at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020) ~[na:1.8.0_191]
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127) ~[na:1.8.0_191]
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_191]
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[na:1.8.0_191]
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[na:1.8.0_191]
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
... 15 common frames omitted
2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - Repo Count 1 1s
2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - New Commits 0 1s
2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - New Pulls 0 1s
2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - New Issues 0 1s
2019-02-27 01:44:01,667 INFO c.c.d.collector.CollectorTask - Finished 1s
public account .. and my properties file
dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
github.key=bUlSRZidDsiu3OmAwRParb8V47CM8g73
logging.file=./logs/github.log
github.cron=0 0/1 * * * *
github.host=https://github.com/poojithkumar/demo/
github.commitThresholdDays=15
github.errorThreshold=1
github.personalAccessToken=given
github.connectTimeout=20000
github.readTimeout=20000
github.username=given
github.password=given

thanks

**Comment by rikameajay1** [comment] 2019-02-27 11:08
@poojithkumar github.username and github.password isn't required.
and change github.host to https://github.com/ and if the repo is public personalaccesstoken is also not needed, but keeping it is no harm.

I tried pulling your github repo and is worked

**Comment by poojithkumar** [comment] 2019-02-27 13:42
And I think host name is also not a problem ... it's not going to deal this
error

**Comment by Sbrenthughes** [comment] 2019-02-27 13:54
What command are you using to run this. And your host shouldn’t be the url to your repo.

**Comment by poojithkumar** [comment] 2019-02-27 14:20
With correct jar version.and path

java -jar github-collector.jar --spring.config.name=github
--spring.config.location=[path to application.properties file]

**Comment by Sbrenthughes** [comment] 2019-02-27 14:26
From the ui repo widget did you try to add a token? If so clear it and try again.

**Comment by poojithkumar** [comment] 2019-02-27 15:57
Yup.. I added that. In ui and github properties file .. i remember , first
I tried without key since I get error I added that.
 Thank you for the response. I will try that also.

**Comment by poojithkumar** [comment] 2019-02-28 04:29
-----------------
2019-02-27 20:21:00,056 INFO  c.c.d.collector.CollectorTask - Starting...
2019-02-27 20:21:00,057 INFO  c.c.d.collector.CollectorTask -
------------------
-----------------
2019-02-27 20:21:00,530 INFO  c.c.d.collector.GitHubCollectorTask -
{password=,
personalAccessToken=, branch=master, userID=, url=
https://github.com/poojithkuma
r/f}::master:: get commits
2019-02-27 20:21:00,536 INFO  c.c.d.collector.DefaultGitHubClient -
Executing
ht
tps://
api.github.com/repos/poojithkumar/f/commits?sha=master&since=2019-02-13T20
:21Z
2019-02-27 20:21:01,250 ERROR c.c.d.collector.GitHubCollectorTask - Error
fetchi
ng commits for:https://github.com/poojithkumar/f
org.springframework.web.client.ResourceAccessException: I/O error on GET
request
for "
https://api.github.com/repos/poojithkumar/f/commits?sha=master&since=2019-
02-13T20:21Z": Received fatal alert: access_denied; nested exception is
javax.ne
t.ssl.SSLHandshakeException: Received fatal alert: access_denied
        at
org.springframework.web.client.RestTemplate.doExecute(RestTemplate.ja
va:607) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at
org.springframework.web.client.RestTemplate.execute(RestTemplate.java
:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at
org.springframework.web.client.RestTemplate.exchange(RestTemplate.jav
a:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at
com.capitalone.dashboard.collector.DefaultGitHubClient.makeRestCall(D
efaultGitHubClient.java:606) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at
com.capitalone.dashboard.collector.DefaultGitHubClient.getCommits(Def
aultGitHubClient.java:106) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at
com.capitalone.dashboard.collector.GitHubCollectorTask.collect(GitHub
CollectorTask.java:178) ~[github-scm-collector-3.0.1.jar!/:3.0.1]
        at
com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.ja
va:63) [core-3.0.4.jar!/:3.0.1]
        at
org.springframework.scheduling.support.DelegatingErrorHandlingRunnabl
e.run(DelegatingErrorHandlingRunnable.java:54)
[spring-context-4.2.5.RELEASE.jar
!/:4.2.5.RELEASE]
        at
org.springframework.scheduling.concurrent.ReschedulingRunnable.run(Re
schedulingRunnable.java:81)
[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1) [na:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[na:1.8.0_20
1]
        at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
        at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_201]
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1149) [na:1.8.0_201]
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:624) [na:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert:
access_den
ied
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
~[na:1.8.0_2
01]
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
~[na:1.8.0_2
01]
        at
sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020)
~[n
a:1.8.0_201]
        at
sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127)
~[
na:1.8.0_201]
        at
sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.
java:1367) ~[na:1.8.0_201]
        at
sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395
) ~[na:1.8.0_201]
        at
sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379
) ~[na:1.8.0_201]
        at
org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSock
et(SSLConnectionSocketFactory.java:394) ~[httpclient-4.5.1.jar!/:4.5.1]
        at
org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSL
ConnectionSocketFactory.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
        at
org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect
(DefaultHttpClientConnectionOperator.java:134)
~[httpclient-4.5.1.jar!/:4.5.1]
        at
org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(
PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
        at
org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClie
ntExec.java:380) ~[httpclient-4.5.1.jar!/:4.5.1]
        at
org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.
java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
        at
org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java
:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at
org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
~
[httpclient-4.5.1.jar!/:4.5.1]
        at
org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java
:110) ~[httpclient-4.5.1.jar!/:4.5.1]
        at
org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttp
Client.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
        at
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
        at
org.springframework.http.client.HttpComponentsClientHttpRequest.execu
teInternal(HttpComponentsClientHttpRequest.java:91)
~[spring-web-4.2.5.RELEASE.j
ar!/:4.2.5.RELEASE]
        at
org.springframework.http.client.AbstractBufferingClientHttpRequest.ex
ecuteInternal(AbstractBufferingClientHttpRequest.java:48)
~[spring-web-4.2.5.REL
EASE.jar!/:4.2.5.RELEASE]
        at
org.springframework.http.client.AbstractClientHttpRequest.execute(Abs
tractClientHttpRequest.java:53)
~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at
org.springframework.web.client.RestTemplate.doExecute(RestTemplate.ja
va:596) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        ... 15 common frames omitted
2019-02-27 20:21:01,261 INFO  c.c.d.collector.CollectorTask - Repo
Count
1        1s
2019-02-27 20:21:01,262 INFO  c.c.d.collector.CollectorTask - New
Commits
0        1s
2019-02-27 20:21:01,262 INFO  c.c.d.collector.CollectorTask - New
Pulls
0        1s
2019-02-27 20:21:01,262 INFO  c.c.d.collector.CollectorTask - New
Issues
0        1s
2019-02-27 20:21:01,262 INFO  c.c.d.collector.CollectorTask -
Finished
1s
2019-02-27 20:22:00,003 INFO  c.c.d.collector.CollectorTask - Running
Collector: GitHub
2019-02-27 20:22:00,022 INFO  c.c.d.collector.CollectorTask -
-----------------------------------
2019-02-27 20:22:00,022 INFO  c.c.d.collector.CollectorTask - Starting...
2019-02-27 20:22:00,022 INFO  c.c.d.collector.CollectorTask -
-----------------------------------
2019-02-27 20:22:00,203 INFO  c.c.d.collector.CollectorTask - Repo
Count              1        0s
2019-02-27 20:22:00,204 INFO  c.c.d.collector.CollectorTask - New
Commits             0        0s
2019-02-27 20:22:00,204 INFO  c.c.d.collector.CollectorTask - New
Pulls               0        0s
2019-02-27 20:22:00,204 INFO  c.c.d.collector.CollectorTask - New
Issues              0        0s
2019-02-27 20:22:00,204 INFO  c.c.d.collector.CollectorTask -
Finished                         0s
2019-02-27 20:23:00,002 INFO  c.c.d.collector.CollectorTask - Running
Collector: GitHub
2019-02-27 20:23:00,031 INFO  c.c.d.collector.CollectorTask -
-----------------------------------


properties file

dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
logging.file=./logs/github.log
github.cron=0 0/1 * * * *
github.host=https://github.com/
github.commitThresholdDays=15
github.errorThreshold=1
#github.personalAccessToken=239a0255772cb1aaefa2d3f3051ef6b68928a123
github.connectTimeout=20000
github.readTimeout=20000


thanks

**Comment by Sbrenthughes** [comment] 2019-06-28 18:45
PR has been merged to resolve this issue. Please update to the latest and open a new issue if you face any problems

**Closed by Sbrenthughes** 2019-06-28 18:45 UTC
Labels: enhancement, help wanted
