### ISSUE TITLE
Product Dashboard-can not support Subverion Commit data

### ISSUE THREAD

**Issue by wwei1896** [Hygieia/Hygieia#2866] opened 2019-04-30 09:42 UTC
Hi,
I can not get the Subversion Commit data show in Product Dashboard, can you help check if it is support in the latest version?
![image](https://user-images.githubusercontent.com/46481026/56953509-500bc000-6b6f-11e9-9554-b4b8577d2955.png)

Thanks

**Comment by Sbrenthughes** [comment] 2019-04-30 17:35
Duplicate of https://github.com/Hygieia/Hygieia/issues/2347

**Closed by Sbrenthughes** 2019-04-30 17:35 UTC
