### ISSUE TITLE
Enable ldap for Hygieia 

### ISSUE THREAD

**Issue by ojasvijagtap** [Hygieia/Hygieia#2914] opened 2019-05-16 20:59 UTC
I am getting "Bad credentials" error while attempting to authenticate through Ldap from Hygieia. 
I read almost all the issues posted related to hygieia + Ldap and AD too. 
But didnt any solution work for me. 

**api property file:**
# JWT expiration time in milliseconds
auth.expirationTime=600

# Secret Key used to validate the JWT tokens
auth.secret=${AUTH_SECRET:-}
auth.authenticationProviders=LDAP,STANDARD

# LDAP Server Url, including port of your LDAP server
auth.ldapServerUrl=ldap://xxxx:port/DC=xxx,DC=xxx
auth.ldapUserDnPattern=uid={0},CN={0},OU=Application,OU=ServiceAccounts,DC=xxx,DC=xxx
auth.ldapDisableGroupAuthorization=${AUTH_LDAP_DISABLE_GROUP_AUTHORIZATION:-false}
logging.level.com.capitalone.dashboard=DEBUG

# Needed if you want to query ldap
auth.ldapBindUser=user
auth.ldapBindPass=password

**API logs:**
2019-05-16 20:48:15,294 INFO  o.s.s.l.DefaultSpringSecurityContextSource -  URL 'ldap://xxxx:port/DC=xxx,DC=xxx', root DN is 'DC=xxx,DC=xxx'
2019-05-16 20:48:15,418 INFO  o.s.l.c.s.AbstractContextSource - **Property 'userDn' not set** - anonymous context will be used for read-write operations
2019-05-16 20:48:16,432 INFO  o.s.s.l.u.DefaultLdapAuthoritiesPopulator - groupSearchBase is empty. Searches will be performed from the context source base

**API logs errors onlogin attempt:**
2019-05-16 20:50:38,068 DEBUG c.c.d.a.ldap.LdapLoginRequestFilter - Request is to process authentication
2019-05-16 20:50:38,103 DEBUG c.c.d.a.ldap.LdapLoginRequestFilter - Authentication request failed: org.springframework.security.authentication.BadCredentialsException: **Bad credentials**
2019-05-16 20:50:38,103 DEBUG c.c.d.a.ldap.LdapLoginRequestFilter - Updated SecurityContextHolder to contain null Authentication
2019-05-16 20:50:38,103 DEBUG c.c.d.a.ldap.LdapLoginRequestFilter - Delegating to authentication failure handler org.springframework.security.web.authentication.SimpleUrlAuthenticationFailureHandler@71dbb61a

Note: I have verified that my ldap URL and credentials are correct. 

Can you please help here to find the issue?

**Comment by Sbrenthughes** [comment] 2019-05-22 14:36
Working on this. Will get back to you.

**Comment by Sbrenthughes** [comment] 2019-05-23 17:46
But closing this as this is a duplicate of https://github.com/Hygieia/Hygieia/issues/2839

**Closed by Sbrenthughes** 2019-05-23 17:46 UTC
