### ISSUE TITLE
Question - Hygieia Jenkins Plugin - JUnit support?

### ISSUE THREAD

**Issue by ernieshu** [Hygieia/Hygieia#666] opened 2016-06-30 19:12 UTC
Hi folks,

Very new to Hygieia - looking at v2.0.0 - and within the Hygieia Jenkins Plugin, it looks like it only supports sending Cucumber Test results to Hygieia - is that correct?  Or am I missing some kind of configuration / JUnit test parser for surefire reports that exists already?  

As the Use Case we're looking for is being able to send JUnit results (surefire-reports or the like) to Hygieia ... hoping utilize whatever work has been contributed to this point, prior to trying to put something together ourselves ...

Cheers, thank you!

Ernie Shu

**Comment by tabladrum** [comment] 2016-07-05 13:38
Junit results are pulled in via Sonar.

**Comment by ernieshu** [comment] 2016-07-05 15:56
Thanks @tabladrum !  

Had a bit more time to poke around - I can see the JUnit results end up getting stored in Mongo, under collection 'code_quality', for Sonar as you pointed out?  But only Cucumber results get stored under collection 'test_results', corresponding with widget 'Quality' section 'Functional Tests'?  

Presuming there's no collector (as of right now) for JUnit test runners in Jenkins / Sonar to populate 'test_results'?  

Thanks again!

Ernie Shu

**Comment by sthatip** [comment] 2016-07-05 18:44
@ernieshu I had a similar requirement, myproject setup was not suitable to update Sonar and had to pull Junit results from Jenkins. I ended up writing a new collector very similar to cucumber collector and update test_results collection and separate them out in UI with a testType field. 

I think code quality widget could have been separate widgets. I have an app that uses UFT for functional tests and now integrating that into quality widget.

**Comment by tabladrum** [comment] 2016-07-14 20:44
I think the Jenkins plugin can be enhanced to do this. Let me know your progress. Thanks

**Comment by ernieshuiwd** [comment] 2016-07-19 02:42
Thanks gents both for your responses!

**Comment by Saravanavel04** [comment] 2016-09-19 07:25
@ernieshuiwd will you provide more details on this to get a Junit reports.?

**Comment by ernieshuiwd** [comment] 2016-09-21 05:36
@Saravanavel04 - this request was about populating JUnit test results in the way that Cucumber test results were stored + displayed in the Team Dashboard.  Agree that with @tabladrum that the path of least resistance was to utilize the Jenkins plugin (which works very seamlessly, I might add) - however, the direction we're moving in is to have everything in Pipeline jobs - which currently precludes the use of said plugin.  (@sthatip had a different suggestion as well, which would work as well). We wrote some custom scripts to publish build + artifact info, but were hoping to convert into a proper Jenkins hpi that supports pipeline.

**Comment by tabladrum** [comment] 2018-10-29 14:08
Closed as the current plugin supports it.

**Closed by tabladrum** 2018-10-29 14:08 UTC

**Comment by keir-lavelle** [comment] 2019-11-06 17:35
Hygieia Publisher Plugin Version: 2.2.3
Jenkins Version: 2.190.1

Hi there, sorry to bring back up a closed issue but it's mentioned that current plugin supports Junit.xml publishing from a pipeline defined with Jenkinsfile, however I am getting an error 

`Hygieia Test Publisher: Processing read error /var/lib/jenkins/workspace/form-ci-pipelines_pup-api_master/junit.xml`

I have checked the validity of the generated XML file against the junit XSD and confirmed that the document is valid. 

The path is correct (when the path is incorrect I just receive a "nothing to publish" message) and my call in the Jenkinsfile looks like so:

`hygieiaTestPublishStep buildStatus: 'Success', testApplicationName: 'pup-api', testEnvironmentName: params.environment, testFileNamePattern: 'junit.xml', testResultsDirectory: '', testType: 'Unit'`

Can you please advise as to what I might be doing wrong?
