### ISSUE TITLE
what does github-graphql collector do and how to run this collector?

### ISSUE THREAD

**Issue by gopiprasanthpotipireddy** [Hygieia/Hygieia#2985] opened 2019-06-20 05:34 UTC
I found github-graphql collector and what does it collect and can any one give properties configuration for this collector.

**Comment by rvema** [comment] 2019-06-20 18:25
This is the github collector which leverages the graphql api offered by github. Please ping me in private so that I can help with properties for the same.

**Comment by gopiprasanthpotipireddy** [comment] 2019-06-21 04:52
okay sure @rvema thankyou, i will ping you.

**Comment by rvema** [comment] 2019-06-28 17:25
dbname=dashboarddb
dbhost=
dbport=
dbusername=
dbpassword=

#every 5 minutes
github.cron=0 */5 * * * MON-SAT

github.firstRunHistoryDays=60
github.errorThreshold=1
github.rateLimitThreshold=100
github.host=
github.key=

github.personalAccessToken=

github.commitPullSyncTime=604800000

github.offsetMinutes=120

github.fetchCount=100

#github rest call parameters
github.connectTimeout=20000
github.readTimeout=60000

**Comment by rvema** [comment] 2019-06-28 17:26
@gopiprasanthpotipireddy Can you check if the above is good enough? do fill the DB credentials and host information

**Comment by gopiprasanthpotipireddy** [comment] 2019-07-01 06:31
okay @rvema i will check and come back.

**Comment by gopiprasanthpotipireddy** [comment] 2019-07-01 06:48
@rvema when i run the collector its is giving the following error

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.core.MongoTemplate]: Factory method 'mongoTemplate' threw exception; nested exception is java.lang.IllegalArgumentException: Database name must only contain letters, numbers, underscores and dashes!
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 47 more
Caused by: java.lang.IllegalArgumentException: Database name must only contain letters, numbers, underscores and dashes!
        at org.springframework.util.Assert.isTrue(Assert.java:68)
        at org.springframework.data.mongodb.core.SimpleMongoDbFactory.<init>(SimpleMongoDbFactory.java:143)
        at org.springframework.data.mongodb.core.SimpleMongoDbFactory.<init>(SimpleMongoDbFactory.java:78)
        at org.springframework.data.mongodb.core.SimpleMongoDbFactory.<init>(SimpleMongoDbFactory.java:65)
        at org.springframework.data.mongodb.core.MongoTemplate.<init>(MongoTemplate.java:181)
        at com.capitalone.dashboard.config.MongoConfig.mongoTemplate(MongoConfig.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by gopiprasanthpotipireddy** [comment] 2019-07-01 06:48
my properties file
dbname=dashboard	

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

#every 5 minutes
#github.cron=0 */5 * * * MON-SAT

# Collector schedule (required)
github.cron=0/30 * * * * *


github.firstRunHistoryDays=60
github.errorThreshold=1
github.rateLimitThreshold=100
github.host=github.com
github.key=

github.personalAccessToken=22bc3aead307eaadd93e597c74e8d3db67d9a046

github.commitPullSyncTime=604800000

github.offsetMinutes=120

github.fetchCount=100

#github rest call parameters
github.connectTimeout=20000
github.readTimeout=60000

**Comment by rvema** [comment] 2019-07-01 07:24
dbname should be dashboarddb

**Comment by gopiprasanthpotipireddy** [comment] 2019-07-01 09:14
actually i am using dashboard for hygieia api and all collectors

**Comment by gopiprasanthpotipireddy** [comment] 2019-07-01 09:47
i tried giving dashboarddb still same error

**Comment by rvema** [comment] 2019-07-29 00:24
closing the issue as it was resolved

**Closed by rvema** 2019-07-29 00:24 UTC

**Comment by ShovanDhara** [comment] 2022-06-29 08:45
> d giving dashboarddb still same error

It means the issue is not resolved
