### ISSUE TITLE
Error connecting to db:27017 (172.18.0.3:27017) :: caused by :: Connection refused :

### ISSUE THREAD

**Issue by dasaradhan** [Hygieia/Hygieia#3170] opened 2019-10-17 03:42 UTC
MongoDB shell version v4.2.0
connecting to: mongodb://db:27017/admin?compressors=disabled&gssapiServiceName=mongodb
2019-10-17T03:30:21.633+0000 E  QUERY    [js] Error: couldn't connect to server db:27017, connection attempt failed: SocketException: Error connecting to db:27017 (172.18.0.3:27017) :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:341:17
@(connect):2:6

**Comment by Sbrenthughes** [comment] 2019-10-17 19:46
Can you downgrade to 3.* version of mongo and try again?

**Comment by dasaradhan** [comment] 2019-10-18 03:45
downgraded to 3-xenial but still same issue.

Please suggest

**Comment by dasaradhan** [comment] 2019-10-18 04:11
Containers are going to exited state:
![image](https://user-images.githubusercontent.com/29045180/67065130-c38ba300-f18a-11e9-8642-7cc08832cf1c.png)


Error log for :db-setup_1
![image](https://user-images.githubusercontent.com/29045180/67065172-e3bb6200-f18a-11e9-9ef1-65104044baa4.png)


Error log for:mongo:3.6
![image](https://user-images.githubusercontent.com/29045180/67065202-fcc41300-f18a-11e9-8113-a79c67d8e069.png)


Error log for hygieia collector:
![image](https://user-images.githubusercontent.com/29045180/67065287-59bfc900-f18b-11e9-8d3a-0746e22473f8.png)


Docker.compose.yml:
=================
version: '3'
services:
db:
image: mongo:3.6
ports:
- "27017:27017"
volumes:
- "db-data:/data/db_1"

db-setup:
build: db
depends_on:
- db

api:
image: hygieia-api
depends_on:
- db
environment:
- AUTH_EXPIRATION_TIME= 36000
- AUTH_SECRET= secret

ui:
build: UI
image: hygieia-ui
stdin_open: true
tty: true
depends_on:
- api
ports:
- "8000:80"

hygieia-build-jenkins-collector:
build: hygieia-build-jenkins-collector
image: hygieia-build-jenkins-collector
depends_on:
- db-setup

volumes:
db-data:
certs:

docker-compose.override.yml:
===========================
version: '3'
services:
hygieia-build-jenkins-collector:

environment:
- JENKINS_CRON= 0 * * * * *
- JENKINS_MASTER= http://3.16.22.132:8080
- JENKINS_USERNAME= Dragon
- JENKINS_API_KEY= 11df470af887b7e5051d7d22a79943ae59
- MONGO_PORT= 27017
- MONGO_HOST= 27017

hygieia-build-jenkins-collector:
=======================
FROM openjdk:8-jre

VOLUME ["/hygieia/logs"]

RUN mkdir /hygieia/config

EXPOSE 8080

ENV PROP_FILE /hygieia/config/application.properties

RUN chmod -R a+x /hygieia

WORKDIR /hygieia

COPY target/*.jar /hygieia
COPY docker/properties-builder.sh /hygieia/
RUN sed -i -e 's/\r$//' ./properties-builder.sh

CMD ./properties-builder.sh &&
java -Djava.security.egd=file:/dev/./urandom -jar *.jar --spring.config.location=$PROP_FILE

Please help here to resolve this issue

**Comment by dasaradhan** [comment] 2019-10-18 10:59
Can someone please help here

**Comment by rvema** [comment] 2019-10-31 23:30
This is a duplicate of #3178

**Closed by rvema** 2019-10-31 23:30 UTC
